# Generated by Django 5.2.3 on 2025-08-22 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('url_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_type', models.IntegerField(choices=[(1, 'Cellphone'), (2, 'Landline')])),
                ('number_e164', models.CharField(max_length=15)),
                ('is_principal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(blank=True, choices=[(1, 'Masculine'), (2, 'Feminine'), (3, 'Hidden')], null=True)),
                ('date_birth', models.DateField()),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('average_delivery_time', models.SmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
