# Generated by Django 5.2.1 on 2025-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_type', models.IntegerField(choices=[(1, 'Cellphone'), (2, 'Landline')])),
                ('number_e164', models.CharField(max_length=15)),
                ('is_principal', models.BooleanField()),
            ],
        ),
    ]
