# Generated by Django 5.2.6 on 2025-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_naturalperson_cnh_remove_naturalperson_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cnpj',
            field=models.CharField(default=1, max_length=14, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
