# Generated by Django 5.2.6 on 2025-09-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurant_cnpj_alter_restaurant_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='neighborhood',
            new_name='district',
        ),
    ]
