# Generated by Django 5.2.1 on 2025-06-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_alter_category_options_category_url_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(choices=[(1, 'Masculine'), (2, 'Feminine'), (3, 'Hidden')], null=True)),
                ('date_birth', models.DateField()),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
