# Generated by Django 5.2.1 on 2025-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculine'), (2, 'Feminine'), (3, 'Hidden')], null=True),
        ),
    ]
