# Generated by Django 5.2.6 on 2025-09-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewrestaurant_responsereviewrestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='note',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
