# Generated by Django 5.2.6 on 2025-09-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reviewrestaurant_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsereviewrestaurant',
            old_name='autor',
            new_name='author',
        ),
    ]
