# Generated by Django 5.2.3 on 2025-06-17 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_naturalperson_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=7, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='core.color')),
                ('idMark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='core.mark')),
                ('idNaturalPerson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
