# Generated by Django 5.2.6 on 2025-09-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_autor_responsereviewrestaurant_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsereviewrestaurant',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
