# Generated by Django 5.2.3 on 2025-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_color_mark_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='tipe',
            new_name='type_vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
