# Generated by Django 5.2.6 on 2025-09-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_responsereviewrestaurant_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsereviewrestaurant',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ReviewDeliveryman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_deliveryman', to=settings.AUTH_USER_MODEL)),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseReviewDeliveryman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.reviewdeliveryman')),
            ],
        ),
    ]
