# Generated by Django 5.2.3 on 2025-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ativo_vehicle_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='url_crlv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
