# Generated by Django 5.2.3 on 2025-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_color_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
