# Generated by Django 5.2.6 on 2025-09-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_datetime_responsereviewrestaurant_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdeliveryman',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.order', unique=True),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.order', unique=True),
        ),
    ]
