# Generated by Django 5.2.3 on 2025-07-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vehicle_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='idColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='idMark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.mark'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='idNaturalPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.naturalperson'),
        ),
    ]
