# Generated by Django 5.2.6 on 2025-09-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reviewdeliveryman_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdeliveryman',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.order'),
        ),
        migrations.AlterField(
            model_name='reviewrestaurant',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.order'),
        ),
    ]
