# Generated by Django 5.2.6 on 2025-09-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reviewdeliveryman_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='price',
        ),
    ]
