# Generated by Django 5.2.6 on 2025-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_value_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
