# Generated by Django 5.2.3 on 2025-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
