# Generated by Django 5.2.3 on 2025-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_restaurant_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
