# Generated by Django 5.2.6 on 2025-09-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recentlyviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='quantityOrders',
            field=models.IntegerField(default=0),
        ),
    ]
