# Generated by Django 5.2.6 on 2025-09-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restaurant_quantityorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='quantityOrders',
        ),
    ]
