# Generated by Django 5.2.6 on 2025-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_restaurant_quantityorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviews',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
