# Generated by Django 5.2.6 on 2025-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_recentlyviews_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='public_id_cloudinary',
            field=models.CharField(default='', max_length=40),
        ),
    ]
