# Generated by Django 5.2.6 on 2025-10-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_recentlyviews_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
