# Generated by Django 5.2.3 on 2025-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_restaurant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='+', to='core.category'),
        ),
    ]
