# Generated by Django 5.2.6 on 2025-10-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_category_public_id_cloudinary_and_more'),
        ('core', '0020_alter_naturalperson_date_birth'),
    ]

    operations = [
    ]
