# Generated by Django 5.2.3 on 2025-08-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Delivering'), (4, 'Delivered')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordersClient', to='core.naturalperson')),
                ('deliveryMan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordersDelivery', to='core.naturalperson')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.restaurant')),
            ],
            options={
                'unique_together': {('client', 'deliveryMan')},
            },
        ),
    ]
