# Generated by Django 5.2.3 on 2025-08-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('deliverymen', 'client')},
        ),
    ]
