# Generated by Django 5.2.3 on 2025-08-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
