# Generated by Django 5.2.3 on 2025-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
    ]
