# Generated by Django 5.2.6 on 2025-10-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_favorite_unique_client_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cart'), (2, 'Payment'), (3, 'Pending'), (4, 'Preparing'), (5, 'Delivering'), (6, 'Delivered')], default=3),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cart'), (2, 'Payment'), (3, 'Pending'), (4, 'Preparing'), (5, 'Delivering'), (6, 'Delivered')]),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.product'),
        ),
    ]
