# Generated by Django 5.2.3 on 2025-08-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_url_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_field',
            new_name='url_file',
        ),
    ]
