# Generated by Django 5.2.6 on 2025-10-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_order_status_alter_orderstatuslog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cart'), (2, 'Pending'), (3, 'Preparing'), (4, 'Delivering'), (5, 'Delivered')], default=2),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cart'), (2, 'Pending'), (3, 'Preparing'), (4, 'Delivering'), (5, 'Delivered')]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction_mp', models.IntegerField()),
                ('method', models.IntegerField(choices=[(1, 'Pix'), (2, 'Credit Card'), (3, 'Debit Card')])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='core.order')),
            ],
        ),
    ]
