# Generated by Django 5.2.3 on 2025-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_url_field_product_url_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
