# Generated by Django 5.2.5 on 2025-09-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_url_field_product_url_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('decription', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coupons', to='core.naturalperson')),
                ('idCoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_clients', to='core.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='CouponClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coupons_orders', to='core.naturalperson')),
                ('idCoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_client_orders', to='core.coupon')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coupons', to='core.order')),
            ],
        ),
    ]
