# Generated by Django 5.2.3 on 2025-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_coupon_couponclient_couponclientorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
