# Generated by Django 5.2.6 on 2025-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_payment_qr_code_payment_qr_code_base64_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id_transaction_mp',
            field=models.PositiveBigIntegerField(),
        ),
    ]
