# Generated by Django 5.2.6 on 2025-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_payment_id_transaction_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
