# Generated by Django 5.2.5 on 2025-09-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_naturalperson_name'),
        ('core', '0026_rename_decription_coupon_description_and_more'),
    ]

    operations = [
    ]
