# Generated by Django 5.2.6 on 2025-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_category_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
