# Generated by Django 5.2.3 on 2025-09-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20250902_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponclient',
            old_name='idClient',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='couponclient',
            old_name='idCoupon',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='couponclientorder',
            old_name='idClient',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='couponclientorder',
            old_name='idCoupon',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='couponclientorder',
            old_name='idOrder',
            new_name='order',
        ),
    ]
