# Generated by Django 5.2.3 on 2025-09-02 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_coupon_discount_alter_coupon_max_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couponclientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coupons_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
