# Generated by Django 5.2.3 on 2025-09-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_couponclient_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='idColor',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='idMark',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='idNaturalPerson',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deliveryman',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordersClient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryMan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordersDelivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
