# Generated by Django 5.2.3 on 2025-09-02 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_idcolor_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
