# Generated by Django 5.2.3 on 2025-09-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryMan',
            new_name='deliveryman',
        ),
    ]
