# Generated by Django 5.2.3 on 2025-09-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20250904_1448'),
        ('core', '0034_productorder'),
    ]

    operations = [
    ]
