# Generated by Django 5.2.3 on 2025-09-04 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_0027_merge_20250904_1448_0034_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Delivering'), (4, 'Delivered')])),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusLogs', to='core.order')),
            ],
        ),
    ]
