from .user import UserRegisterSerializer, ListUserSerializer, UpdateUserSerializer
from .category import CategorySerializer, ProductCategorySerializer
from .telephone import TelephoneSerializer
from .address import AddressSerializer
from .natural_person import NaturalPersonSerializer
from .restaurant import RestaurantSerializer, CreateRestaurantSerializer, RetrieveRestaurantSerializer, ListRestaurantSerializer, RecentlyViewsSerializer, ListRecentlyViewsSerializer
from .vehicle import VehicleSerializer, UpdateVehicleSerializer
from .mark import MarkSerializer
from .color import ColorSerializer
from .product import ProductSerializer, ListProductSerializer, RetrieveProductSerializer
from .favorite import FavoriteSerializer
from .order import OrderListSerializer, OrderRetrieveSerializer, CreateOrderSerializer, DeliveryManAcceptOrderSerializer, ProductOrderSerializer
from .coupon import CouponSerializer, CouponClientSerializer, CouponClientOrderSerializer
from .review_restaurant import ReviewRestaurantSerializer, UpdateReviewRestaurantSerializer, ResponseReviewRestaurantSerializer, UpdateResponseReviewRestaurantSerializer
from .review_deliveryman import ReviewDeliverymanSerializer, UpdateReviewDeliverymanSerializer, ResponseReviewDeliverymanSerializer, UpdateResponseReviewDeliverymanSerializer