# Generated by Django 5.2.1 on 2025-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role_register',
            field=models.BooleanField(default=False),
        ),
    ]
