# Generated by Django 5.2.6 on 2025-09-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
