# Generated by Django 5.2.1 on 2025-06-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_role_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='role_register',
        ),
    ]
