# Generated by Django 5.2.6 on 2025-09-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='public_id_cloudinary',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
