# Generated by Django 5.2.6 on 2025-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_public_id_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='code_validator',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
