# Generated by Django 5.2.6 on 2025-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_code_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='code_validator',
            field=models.CharField(default='', max_length=6),
        ),
    ]
