# Generated by Django 5.2.6 on 2025-10-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_code_validator_emailverificationuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationUser',
        ),
    ]
